
      // USESTATE-1 CODE

// import { useState } from "react"
// const App = () => {
// const [num ,SetNum] =useState (23)
// const [user,SetUser] = useState("SAISH")

//   function ChngeStyle () {
//     SetNum(30)
//     SetUser("SARA")
//   }

//   return (
//     <>
//     <h1> THE NUMBER IS {num}</h1> <br /> <h2>USER NAME IS {user}</h2>
//     <button onClick={ChngeStyle}> CLICK ME</button>
//     </>
//   )
// }

// export default App
